apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: multus-access
  namespace: tektontest
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ["network-attachment-definitions"]
    verbs: ["get", "list", "watch"]
