apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-hpa
  namespace: tektontest
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1    # version 변경
    kind: DeploymentConfig    # kind 변경
    name: django
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
